#! /bin/bash
#set -x

wifi=$( nmcli device | grep 'wifi')
ethernet=$(nmcli device | grep 'ethernet')

if $(echo ${ethernet} | grep -q 'connected'); then
	echo ""
fi 

if $(echo ${wifi} | grep -q 'connected'); then
	echo ""
fi

case $BLOCK_BUTTON in
  1) nm-connection-editor ;;
esac
