#!/bin/bash
#set -x

volume() {
  #amixer -D $MIXER get $SCONTROL $(capability)
  amixer get Master | grep -E -o '[0-9]{1,3}?%' | head -1
}

#------------------------------------------------------------------------

case $BLOCK_BUTTON in
  1) amixer -q -D pulse set Master Playback Switch toggle || amixer -q set Front toggle ;;  # left click, mute/unmute
  4) amixer -q set Master 2dB+ unmute                 ;; # scroll up, increase
  5) amixer -q set Master 2dB- unmute                 ;; # scroll down, decrease
esac

volume
