return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "css",
        "csv",
        "dockerfile",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "gomod",
        "gosum",
        "gotmpl",
        "html",
        "json",
        "kconfig",
        "lua",
        "sql",
        "ssh_config",
        "terraform",
        "xml",
        "yaml",
        "zig",
      },
    },
  },
}
