#! /bin/sh
#set -x

# variables
CONF="${HOME}/.config/X"
Xoverwrite="${CONF}/.xoverwrite"
Xcustom="${HOME}/.xcustom"
Xrandrc="${HOME}/.xrandrc"
XlaunchD="${CONF}/xlaunchD"
Xmodmap="${CONF}/Xmodmap"
Xdefaults="${CONF}/Xdefaults"
Xuserfont="${HOME}/.fonts"
WM="/usr/bin/i3"


# import X variables
systemctl --user import-environment DISPLAY XAUTHORITY &
if command -v dbus-update-activation-environment >/dev/null 2>&1; then
        dbus-update-activation-environment DISPLAY XAUTHORITY &
fi

# override default variables here
if [ -f ${Xoverwrite} ]; then
	. ${Xoverwrite}
fi

# X settings
if [ -d ${Xuserfont} ]; then	          #
	xset +fp ${Xuserfont}                 # setup user font dir
  xset fp rehash                        # rehash fonts
fi                                        #

# load X aplicantion settings
if [ -f ${Xdefaults} ]; then
	xrdb -merge ${Xdefaults} &
fi

# load X keyboard settings
if [ -f ${Xmodmap} ]; then
	xmodmap ${Xmodmap} &
fi

# include xrandr
if [ -f ${Xrandrc} ]; then
	. ${Xrandrc}
fi

# override settings here
if [ -f ${Xcustom} ]; then
	. ${Xcustom}
fi

# setup touchpad
touchpad_id=$(xinput list --short | grep -i touchpad | cut -f 2 | cut -d = -f 2)
xinput set-prop $touchpad_id "libinput Tapping Enabled" 1 &

# start user services
systemctl --user start x.target &

# 
xset b off

exec ${WM}
