# zprofile

# ssh agent socket
export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/ssh-agent.socket"

# start desktop env 

# start wayland
if [ "$(tty)" = "/dev/tty1" ]; then

  # load zshrc that sway have all settings
  source ~/.zshrc

  # load sway environment
    source ~/.config/sway/environment

  # start sway
	exec sway > ~/.sway.log 2>&1
fi

# startX
#if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
#		  exec startx
#fi
