#


# ssh agent socket
export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/ssh-agent.socket"

# start desktop env 
if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
		  exec startx
fi

#if [ "$(tty)" = "/dev/tty1" ]; then
#	exec sway
  #fi
