#! /bin/zsh
#set -x

###################################################################################
# Startup Files
###################################################################################
# Login files
# #  level   files          interactive-login    interactive-non-login     script
# 1 system   /etc/zshenv    X                    X                         X
# 2 user     ~/.zshenv      X                    X                         X
# 3 system   /etc/zprofile  X
# 4 user     ~/.zprofile    X
# 5 system   /etc/zshrc     X                    X
# 6 user     ~/.zshrc       X                    X
# 7 system   /etc/zlogin    X
# 8 user     ~/.zlogin      X

# Logout Files
# 1. user)    ~/.zlogout    X
# 2. system)  /etc/zlogout  X


###################################################################################
# load settings
###################################################################################
# load libaries
for config_file (${HOME}/.config/zsh/lib/*.zsh); do
    source "${config_file}"
done

###################################################################################
# local settings to override
###################################################################################
[[ -f ${HOME}/.zshrc.local ]] && source ${HOME}/.zshrc.local

###################################################################################
# finish all
###################################################################################
autoload -Uz compinit
compinit

zinit cdreplay -q
