#set -x

# load libaries
for config_file (${HOME}/.config/zsh/lib/*.zsh); do
    source "${config_file}"
done

autoload -U compinit
compinit -i

# PATH
PATH="${HOME}/bin:${PATH}"

# prompt
#export VIRTUAL_ENV_DISABLE_PROMPT=1
#autoload -Uz add-zsh-hook
## prompt_mimir_cmd() { mimir }
#prompt_mimir_cmd() { /home/dgo/projects/mimir/build/mimir }
#add-zsh-hook precmd prompt_mimir_cmd

#prompt_symbol='❯'
#PROMPT='%(?.%F{magenta}.%F{red})${prompt_symbol}%f '
