#! /bin/zsh
#set -x

###################################################################################
# Startup Files
###################################################################################
# Login files
# #  level   files          interactive-login    interactive-non-login     script
# 1 system   /etc/zshenv    X                    X                         X
# 2 user     ~/.zshenv      X                    X                         X
# 3 system   /etc/zprofile  X
# 4 user     ~/.zprofile    X
# 5 system   /etc/zshrc     X                    X
# 6 user     ~/.zshrc       X                    X
# 7 system   /etc/zlogin    X
# 8 user     ~/.zlogin      X

# Logout Files
# 1. user)    ~/.zlogout    X
# 2. system)  /etc/zlogout  X

###################################################################################
# zinit (plugin manager)
###################################################################################
### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing DHARMA Initiative Plugin Manager (zdharma/zinit)…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f" || \
        print -P "%F{160}▓▒░ The clone has failed.%f"
fi
source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
### End of Zinit installer's chunk

###################################################################################
# plugin settings
###################################################################################

# just load the .env file
ZSH_DOTENV_PROMPT=false

###################################################################################
# look and feel
###################################################################################
zinit light zdharma/fast-syntax-highlighting

# prompt
zinit ice compile'(pure|async).zsh' pick'async.zsh' src'pure.zsh'
zinit light sindresorhus/pure

###################################################################################
# functions
###################################################################################

# extract archive .zip
zinit light alexrochas/zsh-extract

# load .env file
zinit snippet OMZ::plugins/dotenv/dotenv.plugin.zsh

zinit light wfxr/forgit

###################################################################################
# load libaries
###################################################################################
for config_file (${HOME}/.config/zsh/lib/*.zsh); do
    source ${config_file}
done

###################################################################################
# local settings to override
###################################################################################
[[ -f ${HOME}/.zshrc.local ]] && source ${HOME}/.zshrc.local

###################################################################################
# finish all
###################################################################################
autoload -Uz compinit
compinit

zinit cdreplay -q
